# Enable display for nice!view v2
CONFIG_ZMK_DISPLAY=y

# Enable mouse emulation (used by Miryoku mouse layer)
CONFIG_ZMK_POINTING=y

# Deep sleep settings
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Custom keyboard name (max. 16 characters)
CONFIG_ZMK_KEYBOARD_NAME="Corne Miryoku"
